version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.8.0
    environment:
      NODE_ENV: circleci
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM cache
          keys:
            - npm-cache-{{ checksum "package.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          name: Persist NPM cache
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - ../.npm
      - run:
          name: Create test results folders
          command: |
            mkdir /tmp/circleci-test-results
            mkdir /tmp/circleci-test-results/jest
      - run:
          name: Run Tests
          command: |
            npm run test -- --ci --coverage --reporters=default --reporters=jest-junit
            npx codecov
          environment:
            JEST_JUNIT_OUTPUT: /tmp/circleci-test-results/jest/results.xml
      - store_test_results:
          path: /tmp/circleci-test-results
